FROM mysql

ENV MYSQL_ROOT_PASSWORD=g8OKo9kiGaXHwziVWu7pI5VyYrbVcSWQd530FPM1Q39Ze5PboO \
    MYSQL_DATABASE=agape \
    MYSQL_USER=agape \
    MYSQL_PASSWORD=GsVfyh9ijn0qPUkWQbI6cNjFmJdkOB2OxG79JiBWANsVS3omaa

COPY init.sql /docker-entrypoint-initdb.d